[package]
name = "game2"
version = "0.1.0"
authors = ["Ivan Ivanov <ivan@ivanovs.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "^0.27.0"
gl = "^0.14.0"
glam = "^0.17.1"
stb_image = "^0.2.3"
gltf = { version = "0.16.0", features = ["names"], default-features = false }
thiserror = "1.0"
memoffset = "0.6.4"

[profile.dev.package."*"]
opt-level = 3
